site_name: ReadySteadyPlug Support
site_url: https://support.readysteadyplug.com

nav:
  - Home: index.md
  - Quick Start Guide:
      - Getting Started: quick_start_guide/index.md  # Displayed as "Getting Started" in the navigation
      #- Page 1: section1/page1.md
  #- Section 2:
  #    - Title for Section 2: section2/index.md  # Displayed as "Title for Section 2"
  #    - Page 2: section2/page2.md


# Custom Homepage Elements
home_cover_image: attachments/charging_setup.png # This path starts at your root mkdocs directory.
home_tagline: ReadySteadyPlug - Let's Go
home_description: |
  Weclome to the support and information pages for ReadySteadyPlug.

# Gradient Color
home_gradient_hsla: hsla(0deg,47%,55%,1) # Default Green: hsla(160deg,47%,55%,1)

# Custom Homepage Button(s)
home_button1_name: Getting Started                  # Comment this parameter out to remove the button.
home_button1_url: Quick Start Guide/                       # This path starts at your root mkdocs directory.
home_button1_theme: md-button md-button--primary # Options: "md-button", "md-button md-button--primary"
home_button1_icon: people                        # Options: "people", "gear", "image"
home_button1_blurb: |                            # Short description of this button / section.
  This joker navigates to the shadow wizard armory located in "/Folder1/index.md"

home_button2_name: Clicky 2   # Comment this parameter out to remove the button.
home_button2_url: Folder2/    # This path starts at your root mkdocs directory.
home_button2_theme: md-button # Options: "md-button", "md-button md-button--primary"
home_button2_icon: gear       # Options: "people", "gear", "image"
home_button2_blurb: |         # Short description of this button / section.
  This goober navigates to some important thingies located in "/Folder2/index.md"

home_button3_name: Clicky 3   # Comment this parameter out to remove the button.
home_button3_url: Folder3/    # This path starts at your root mkdocs directory.
home_button3_theme: md-button # Options: "md-button", "md-button md-button--primary"
home_button3_icon: image      # Options: "people", "gear", "image"
home_button3_blurb: |         # Short description of this button / section.
  This psycho navigates to an interesting table of stuff located in "/Folder3/index.md"

# Homepage Code Execution
home_execute_js: | # Javascript to execute when accessing the homepage
  console.log("This is an example!");

# Material Configuration
theme:
  name: material
  custom_dir: overrides # Contains custom 'home.html' coverpage (and 'main.html')
  logo: assets/logo.svg
  favicon: assets/favicon.png
  features:
    - navigation.tabs             # Static upper section tabs (exist)
    - navigation.tabs.sticky      # Static upper section tabs (stay)
    - navigation.footer           # Add 'previous' and 'next' buttons in the footer
    - navigation.sections
    - navigation.instant          # Keep navigation from reloading
    - toc.integrate
    - navigation.top
    - search.highlight            # Highlight all occurrences of queried string
    - search.share                # Search Query can be copied to Clipboard
    - search.suggest              # Display likeliest completion for the last queried word
    - content.tabs.link
    #- content.code.annotate
    - content.code.copy
  language: en
  palette:
    # Dark Mode
   -  media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: teal
      accent: deep purple

    # Light Mode
    # can be customised via /stylesheets/extra.css
   -  media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: light blue
      accent: deep orange
  
  font:
    text: Figtree
    code: Red Hat Mono
#end theme

extra_css:
  - stylesheets/extra.css

#extra_javascript:
 # - javascript/extra.js

#extra_templates:



plugins:
  - search
 # - roamlinks # Obsidian Style Image Support ![[<attachment_name>]]
 # - callouts #callouts breaks build on Github Workflows. CLI file update required.
 #  - social #social plugin breaks build on Windows

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.mark
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg


copyright: Copyright &copy; 2025 ReadySteadyPlug Pty Limited